import { z } from "zod";
import type { WorkspaceState } from "./contracts";
import type { WorkspaceCommand } from "./workspace-reducer";
import { nextIdeaPosition, nextMathPosition } from "./math-items";

const cardId = z.string().min(1).max(64);
const text = z.string().trim().min(1).max(500);
export const pipActionSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("add_idea"), text }).strict(),
  z.object({ type: z.literal("add_step"), text }).strict(),
  z.object({ type: z.literal("edit_card"), cardId, text }).strict(),
  z.object({ type: z.literal("connect_cards"), fromCardId: cardId, toCardId: cardId }).strict(),
  z.object({ type: z.literal("complete_step"), cardId }).strict(),
  z.object({ type: z.literal("highlight_cards"), cardIds: z.array(cardId).min(1).max(10) }).strict(),
  z.object({ type: z.literal("set_goal"), text: z.string().trim().min(1).max(5000) }).strict(),
  z.object({ type: z.literal("plot_function"), expression: z.string().trim().min(1).max(240), xMin: z.number().min(-1000).max(1000), xMax: z.number().min(-1000).max(1000) }).strict(),
  z.object({ type: z.literal("show_equation"), expression: z.string().trim().min(1).max(240) }).strict(),
]);
export type PipAction = z.infer<typeof pipActionSchema>;

export const pipActionInputSchema = z.object({
  basedOnRevision: z.number().int().nonnegative(),
  actions: z.array(pipActionSchema).min(1).max(5),
}).strict();

// IDs are supplied by application code, never generated by the model.
export const pipActionBatchSchema = pipActionInputSchema.extend({
  batchId: z.string().min(1).max(200),
  resourceIds: z.array(cardId).min(1).max(5),
}).superRefine((batch, ctx) => {
  if (batch.resourceIds.length !== batch.actions.length || new Set(batch.resourceIds).size !== batch.resourceIds.length) {
    ctx.addIssue({ code: "custom", message: "Each action needs its own application ID." });
  }
});
export type PipActionBatch = z.infer<typeof pipActionBatchSchema>;

export function referencedCardIds(action: PipAction): string[] {
  switch (action.type) {
    case "edit_card": case "complete_step": return [action.cardId];
    case "connect_cards": return [action.fromCardId, action.toCardId];
    case "highlight_cards": return action.cardIds;
    default: return [];
  }
}

export function commandFromPipAction(action: PipAction, resourceId: string, workspace: WorkspaceState): WorkspaceCommand {
  switch (action.type) {
    case "plot_function": case "show_equation": {
      return { type: "add-math", item: { id: resourceId, kind: action.type === "plot_function" ? "graph" : "equation", expression: action.expression, xMin: action.type === "plot_function" ? action.xMin : -10, xMax: action.type === "plot_function" ? action.xMax : 10, position: nextMathPosition(workspace) } };
    }
    case "add_idea": case "add_step": {
      return { type: "add-card", card: { id: resourceId, text: action.text, kind: action.type === "add_idea" ? "idea" : "step", status: "active", position: nextIdeaPosition(workspace) } };
    }
    case "edit_card": return { type: "edit-card", cardId: action.cardId, text: action.text };
    case "connect_cards": return { type: "connect", connectionId: resourceId, fromCardId: action.fromCardId, toCardId: action.toCardId };
    case "complete_step": return { type: "complete-step", cardId: action.cardId };
    case "highlight_cards": return { type: "select-cards", cardIds: action.cardIds };
    case "set_goal": return { type: "update-assignment", text: action.text };
  }
}

export function describePipActions(actions: PipAction[]): string {
  return actions.map(action => {
    switch (action.type) {
      case "add_idea": return `Added idea: ${action.text}`;
      case "add_step": return `Added step: ${action.text}`;
      case "edit_card": return `Updated card: ${action.text}`;
      case "connect_cards": return "Connected two cards";
      case "complete_step": return "Completed a step";
      case "highlight_cards": return "Highlighted cards";
      case "set_goal": return `Updated goal: ${action.text}`;
      case "plot_function": return `Plotted ${action.expression} from x = ${action.xMin} to ${action.xMax}`;
      case "show_equation": return `Added equation: ${action.expression}`;
    }
  }).join(" · ");
}
