// Runtime validation for the shared workspace and the Pip text endpoint.
// DRAFT: proposed shapes for the team to review with Chris before anyone builds on them.
// Types for these shapes live in contracts.ts, derived from the schemas so the two never drift.
import { z } from "zod";

const id = z.string().min(1).max(64);

function reportDuplicateValues(
  values: string[],
  path: string,
  ctx: z.RefinementCtx,
) {
  const seen = new Set<string>();

  values.forEach((value, index) => {
    if (seen.has(value)) {
      ctx.addIssue({
        code: "custom",
        message: `Duplicate ${path} value: ${value}`,
        path: [path, index],
      });
    }
    seen.add(value);
  });
}

function reportMissingCard(
  cardId: string,
  cardIds: Set<string>,
  path: PropertyKey[],
  ctx: z.RefinementCtx,
) {
  if (!cardIds.has(cardId)) {
    ctx.addIssue({
      code: "custom",
      message: `Card does not exist: ${cardId}`,
      path,
    });
  }
}

export const requirementSchema = z.object({
  id,
  text: z.string().min(1).max(300),
  // Set by the user. An AI assessment is only ever a suggestion.
  checked: z.boolean(),
});

export const cardSchema = z.object({
  id,
  text: z.string().min(1).max(500),
  kind: z.enum(["idea", "step"]),
  position: z.object({ x: z.number(), y: z.number() }),
  status: z.enum(["active", "aside", "done"]),
  sourceUtterance: z.string().max(1000).optional(),
});

export const connectionSchema = z.object({
  id,
  fromCardId: id,
  toCardId: id,
});

export const conversationTurnSchema = z.object({
  role: z.enum(["user", "pip"]),
  text: z.string().min(1).max(2000),
});

// A card Pip suggests. It is not on the board until the user accepts it.
export const suggestedCardSchema = z.object({
  suggestionId: id,
  text: z.string().min(1).max(500),
  kind: z.enum(["idea", "step"]),
});

// A requirement Pip found in the assignment. It is not on the checklist until the user confirms it.
export const suggestedRequirementSchema = z.object({
  suggestionId: id,
  text: z.string().min(1).max(300),
});

export const nextStepSuggestionSchema = z.object({
  // Generated by application code so retries keep the same identity.
  suggestionId: id,
  text: z.string().min(1).max(200),
});

// Everything Pip has suggested that the user has not accepted or dismissed yet.
// Accepting moves an item into requirements/cards; dismissing removes it.
export const pendingSuggestionsSchema = z.object({
  requirements: z.array(suggestedRequirementSchema).max(20),
  cards: z.array(suggestedCardSchema).max(20),
  nextStep: nextStepSuggestionSchema.nullable(),
});

export const workspaceStateSchema = z
  .object({
    projectId: id,
    title: z.string().min(1).max(120),
    assignment: z.string().max(5000),
    requirements: z.array(requirementSchema).max(20),
    cards: z.array(cardSchema).max(100),
    connections: z.array(connectionSchema).max(200),
    outlineOrder: z.array(id).max(100),
    selectedCardIds: z.array(id).max(100),
    currentStepId: id.nullable(),
    notebookText: z.string().max(50000),
    conversation: z.array(conversationTurnSchema).max(20),
    // Goes up by one on every accepted change, so stale AI replies can be detected.
    revision: z.number().int().min(0),
    coins: z.number().int().min(0),
    rewardEventIds: z.array(z.string().max(100)).max(500),
    ownedDecorations: z.array(z.string().max(64)).max(100),
    pending: pendingSuggestionsSchema,
  })
  .superRefine((workspace, ctx) => {
    reportDuplicateValues(
      workspace.requirements.map(({ id }) => id),
      "requirements",
      ctx,
    );
    reportDuplicateValues(
      workspace.cards.map(({ id }) => id),
      "cards",
      ctx,
    );
    reportDuplicateValues(
      workspace.connections.map(({ id }) => id),
      "connections",
      ctx,
    );
    reportDuplicateValues(workspace.outlineOrder, "outlineOrder", ctx);
    reportDuplicateValues(workspace.selectedCardIds, "selectedCardIds", ctx);
    reportDuplicateValues(workspace.rewardEventIds, "rewardEventIds", ctx);
    reportDuplicateValues(workspace.ownedDecorations, "ownedDecorations", ctx);

    const cardIds = new Set(workspace.cards.map(({ id }) => id));
    workspace.connections.forEach((connection, index) => {
      reportMissingCard(connection.fromCardId, cardIds, ["connections", index, "fromCardId"], ctx);
      reportMissingCard(connection.toCardId, cardIds, ["connections", index, "toCardId"], ctx);
    });
    workspace.outlineOrder.forEach((cardId, index) => {
      reportMissingCard(cardId, cardIds, ["outlineOrder", index], ctx);
    });
    workspace.selectedCardIds.forEach((cardId, index) => {
      reportMissingCard(cardId, cardIds, ["selectedCardIds", index], ctx);
    });

    if (workspace.currentStepId !== null) {
      const currentStep = workspace.cards.find(({ id }) => id === workspace.currentStepId);
      reportMissingCard(workspace.currentStepId, cardIds, ["currentStepId"], ctx);
      if (currentStep && currentStep.kind !== "step") {
        ctx.addIssue({
          code: "custom",
          message: "Current step must reference a step card",
          path: ["currentStepId"],
        });
      }
    }

    const pendingIds = [
      ...workspace.pending.requirements.map(({ suggestionId }) => suggestionId),
      ...workspace.pending.cards.map(({ suggestionId }) => suggestionId),
      ...(workspace.pending.nextStep ? [workspace.pending.nextStep.suggestionId] : []),
    ];
    reportDuplicateValues(pendingIds, "pending", ctx);
  });

export const proposedActionSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("highlight"), cardIds: z.array(id).min(1).max(10) }),
  z.object({ type: z.literal("move-aside"), cardId: id }),
  z.object({ type: z.literal("connect"), fromCardId: id, toCardId: id }),
]);

export const pipTurnRequestSchema = z
  .object({
    requestId: id,
    revision: z.number().int().min(0),
    workspace: workspaceStateSchema,
    userText: z.string().trim().min(1).max(2000),
  })
  .superRefine((request, ctx) => {
    if (request.revision !== request.workspace.revision) {
      ctx.addIssue({
        code: "custom",
        message: "Request revision must match the workspace revision",
        path: ["revision"],
      });
    }
  });

export const pipTurnResponseSchema = z.object({
  requestId: id,
  basedOnRevision: z.number().int().min(0),
  replyText: z.string().min(1).max(1000),
  highlightedCardIds: z.array(id).max(10),
  suggestedRequirements: z.array(suggestedRequirementSchema).max(10),
  suggestedCards: z.array(suggestedCardSchema).max(5),
  suggestedNextStep: nextStepSuggestionSchema.nullable(),
  proposedActions: z.array(proposedActionSchema).max(5),
});

// A model response must be checked against the exact request it answers. Shape
// validation alone cannot prove that referenced card IDs or revisions are valid.
export function pipTurnResponseForRequestSchema(
  request: z.infer<typeof pipTurnRequestSchema>,
) {
  return pipTurnResponseSchema.superRefine((response, ctx) => {
    if (response.requestId !== request.requestId) {
      ctx.addIssue({
        code: "custom",
        message: "Response request ID does not match the request",
        path: ["requestId"],
      });
    }
    if (response.basedOnRevision !== request.revision) {
      ctx.addIssue({
        code: "custom",
        message: "Response is based on a stale workspace revision",
        path: ["basedOnRevision"],
      });
    }

    const cardIds = new Set(request.workspace.cards.map(({ id }) => id));
    reportDuplicateValues(response.highlightedCardIds, "highlightedCardIds", ctx);
    response.highlightedCardIds.forEach((cardId, index) => {
      reportMissingCard(cardId, cardIds, ["highlightedCardIds", index], ctx);
    });
    response.proposedActions.forEach((action, index) => {
      if (action.type === "highlight") {
        reportDuplicateValues(action.cardIds, `proposedActions.${index}.cardIds`, ctx);
        action.cardIds.forEach((cardId, cardIndex) => {
          reportMissingCard(
            cardId,
            cardIds,
            ["proposedActions", index, "cardIds", cardIndex],
            ctx,
          );
        });
      } else if (action.type === "move-aside") {
        reportMissingCard(action.cardId, cardIds, ["proposedActions", index, "cardId"], ctx);
      } else {
        reportMissingCard(
          action.fromCardId,
          cardIds,
          ["proposedActions", index, "fromCardId"],
          ctx,
        );
        reportMissingCard(
          action.toCardId,
          cardIds,
          ["proposedActions", index, "toCardId"],
          ctx,
        );
      }
    });

    reportDuplicateValues(
      [
        ...response.suggestedRequirements.map(({ suggestionId }) => suggestionId),
        ...response.suggestedCards.map(({ suggestionId }) => suggestionId),
        ...(response.suggestedNextStep ? [response.suggestedNextStep.suggestionId] : []),
      ],
      "suggestions",
      ctx,
    );
  });
}

export const apiErrorSchema = z.object({
  error: z.object({
    code: z.enum([
      "invalid_request",
      "stale_revision",
      "rate_limited",
      "ai_unavailable",
      "invalid_ai_output",
    ]),
    message: z.string(),
  }),
});
